### ISSUE TITLE
New CoreNLP 3.7.0 compatibility

### ISSUE THREAD

**Issue by jplu** [dhfbk/tint#12]
Hello,

When will be planned to have a Tint version compatible with the new CoreNLP 3.7.0? As now when I use it I get the following exception:

```
Exception in thread "main" java.lang.NoSuchFieldError: TOKENIZE_AND_SSPLIT
        at eu.fbk.dh.tint.tokenizer.annotators.ItalianTokenizerAnnotator.requirementsSatisfied(ItalianTokenizerAnnotator.java:98)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:465)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:154)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:150)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:137)
```

Thanks.

**Comment by ziorufus** [comment]
We are working on it, most of the code has to be changed and we'd like to maintain the compatibility with CoreNLP 3.6.0 as it is still widely used. Thank you for your message, I'll keep the issue open, so that you will be notified when the update is finished.

**Comment by jplu** [comment]
Thank you for your quick reply!

**Comment by ziorufus** [comment]
The update has started... 2e447f8

**Comment by jplu** [comment]
Awesome ! Waiting the official release then :)

**Comment by ziorufus** [comment]
The update is complete, but not yet tested extensively. See commit 7a9a453
If you want to try, just clone the repository and checkout the corenlp370 branch.

**Comment by jplu** [comment]
Cool! I will further test it during the coming days and let you know if everything is ok.

**Comment by iiegn** [comment]
a very quick first trial (for tint-server) ends here:
```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
18:08:40.426 [main] INFO  eu.fbk.dh.tint.runner.TintServer - starting 0.0.0.0	8012 (Wed Feb 15 18:08:40 CET 2017)...
18:08:40.434 [main] INFO  eu.fbk.dh.tint.runner.outputters.SerializerCollector - Loading serializers
18:08:45.985 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator keyphrase with class eu.fbk.dh.tint.kd.annotator.DigiKdAnnotator
18:08:45.985 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator fake_dep with class eu.fbk.dkm.pikes.depparseannotation.StanfordToConllDepsAnnotator
18:08:45.985 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator timex with class eu.fbk.dh.tint.heideltime.annotator.HeidelTimeAnnotator
18:08:45.986 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator geoloc with class eu.fbk.dh.tint.geoloc.annotator.GeolocAnnotator
18:08:45.986 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator readability with class eu.fbk.dh.tint.readability.ReadabilityAnnotator
18:08:45.986 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator ita_tense with class eu.fbk.dh.tint.tense.TenseAnnotator
18:08:45.986 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator dbps with class eu.fbk.dkm.pikes.twm.LinkingAnnotator
18:08:45.986 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator ita_morpho with class eu.fbk.dh.tint.digimorph.annotator.DigiMorphAnnotator
18:08:45.987 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator ml with class eu.fbk.dkm.pikes.twm.LinkingAnnotator
18:08:45.987 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator ita_toksent with class eu.fbk.dh.tint.tokenizer.annotators.ItalianTokenizerAnnotator
18:08:45.987 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator ita_lemma with class eu.fbk.dh.tint.digimorph.annotator.DigiLemmaAnnotator
18:08:45.988 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ita_toksent
18:08:46.069 [main] INFO  eu.fbk.dh.tint.tokenizer.ItalianTokenizer - Loaded 37 normalization rules
18:08:46.071 [main] INFO  eu.fbk.dh.tint.tokenizer.ItalianTokenizer - Loaded 4 sentence splitting rules
18:08:46.072 [main] INFO  eu.fbk.dh.tint.tokenizer.ItalianTokenizer - Loaded 6 token splitting rules
18:08:46.074 [main] INFO  eu.fbk.dh.tint.tokenizer.ItalianTokenizer - Loaded 9 regular expressions
18:08:46.084 [main] INFO  eu.fbk.dh.tint.tokenizer.ItalianTokenizer - Loaded 285 abbreviations
18:08:46.092 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
18:08:46.115 [main] INFO  edu.stanford.nlp.tagger.maxent.MaxentTagger - warning: no language set, no open-class tags specified, and no closed-class tags specified; assuming ALL tags are open class tags
18:08:46.685 [main] INFO  edu.stanford.nlp.tagger.maxent.MaxentTagger - Reading POS tagger model from models/italian-big.tagger ... done [0.6 sec].
18:08:46.685 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ita_morpho
18:08:46.854 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ita_lemma
18:08:46.856 [main] ERROR eu.fbk.dh.tint.runner.TintServer - error running 0.0.0.0:8012
java.lang.IllegalArgumentException: annotator "ita_lemma" requires annotation "LemmaAnnotation". The usual requirements for this annotator are: unknown
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:460)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:154)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:150)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:137)
	at eu.fbk.dh.tint.runner.TintPipeline.load(TintPipeline.java:36)
	at eu.fbk.dh.tint.runner.TintServer.<init>(TintServer.java:55)
	at eu.fbk.dh.tint.runner.TintServer.main(TintServer.java:110)
```
ideas?

**Comment by ziorufus** [comment]
Oops! Fixed in bc441a8

**Comment by iiegn** [comment]
nice :) got further:
```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
22:44:36.502 [main] INFO  eu.fbk.dh.tint.runner.TintServer - starting 0.0.0.0	8012 (Wed Feb 15 22:44:36 CET 2017)...
22:44:36.527 [main] INFO  eu.fbk.dh.tint.runner.outputters.SerializerCollector - Loading serializers
22:44:48.851 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator keyphrase with class eu.fbk.dh.tint.kd.annotator.DigiKdAnnotator
22:44:48.853 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator fake_dep with class eu.fbk.dkm.pikes.depparseannotation.StanfordToConllDepsAnnotator
22:44:48.854 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator timex with class eu.fbk.dh.tint.heideltime.annotator.HeidelTimeAnnotator
22:44:48.854 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator geoloc with class eu.fbk.dh.tint.geoloc.annotator.GeolocAnnotator
22:44:48.855 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator readability with class eu.fbk.dh.tint.readability.ReadabilityAnnotator
22:44:48.857 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator ita_tense with class eu.fbk.dh.tint.tense.TenseAnnotator
22:44:48.858 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator dbps with class eu.fbk.dkm.pikes.twm.LinkingAnnotator
22:44:48.858 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator ita_morpho with class eu.fbk.dh.tint.digimorph.annotator.DigiMorphAnnotator
22:44:48.858 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator ml with class eu.fbk.dkm.pikes.twm.LinkingAnnotator
22:44:48.859 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator ita_toksent with class eu.fbk.dh.tint.tokenizer.annotators.ItalianTokenizerAnnotator
22:44:48.860 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Registering annotator ita_lemma with class eu.fbk.dh.tint.digimorph.annotator.DigiLemmaAnnotator
22:44:48.861 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ita_toksent
22:44:49.023 [main] INFO  eu.fbk.dh.tint.tokenizer.ItalianTokenizer - Loaded 37 normalization rules
22:44:49.028 [main] INFO  eu.fbk.dh.tint.tokenizer.ItalianTokenizer - Loaded 4 sentence splitting rules
22:44:49.031 [main] INFO  eu.fbk.dh.tint.tokenizer.ItalianTokenizer - Loaded 6 token splitting rules
22:44:49.034 [main] INFO  eu.fbk.dh.tint.tokenizer.ItalianTokenizer - Loaded 9 regular expressions
22:44:49.060 [main] INFO  eu.fbk.dh.tint.tokenizer.ItalianTokenizer - Loaded 285 abbreviations
22:44:49.074 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
22:44:49.108 [main] INFO  edu.stanford.nlp.tagger.maxent.MaxentTagger - warning: no language set, no open-class tags specified, and no closed-class tags specified; assuming ALL tags are open class tags
22:44:50.570 [main] INFO  edu.stanford.nlp.tagger.maxent.MaxentTagger - Reading POS tagger model from models/italian-big.tagger ... done [1.5 sec].
22:44:50.571 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ita_morpho
22:44:50.830 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ita_lemma
22:44:50.831 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
22:44:56.669 [main] INFO  edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from models/ner-ita-nogpe-noiob_gaz_wikipedia_sloppy.ser.gz ... done [5.8 sec].
22:44:56.672 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator depparse
22:44:56.742 [main] INFO  edu.stanford.nlp.parser.nndep.DependencyParser - Loading depparse model file: models/parser-model-1.txt.gz ... 
22:45:05.741 [main] INFO  edu.stanford.nlp.parser.nndep.Classifier - PreComputed 100000, Elapsed Time: 2.215 (s)
22:45:05.741 [main] INFO  edu.stanford.nlp.parser.nndep.DependencyParser - Initializing dependency parser ... done [9.0 sec].
22:45:05.742 [main] INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator fake_dep
Exception in thread "main" java.lang.NoSuchFieldError: TOKENIZE_SSPLIT_POS_DEPPARSE
	at eu.fbk.dkm.pikes.depparseannotation.StanfordToConllDepsAnnotator.requires(StanfordToConllDepsAnnotator.java:65)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:455)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:154)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:150)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:137)
	at eu.fbk.dh.tint.runner.TintPipeline.load(TintPipeline.java:36)
	at eu.fbk.dh.tint.runner.TintServer.<init>(TintServer.java:55)
	at eu.fbk.dh.tint.runner.TintServer.main(TintServer.java:110)

```

**Comment by ziorufus** [comment]
Pull and try again :)

**Comment by iiegn** [comment]
success! :)

**Comment by iiegn** [comment]
i tried to understand the passing/reading of the properties file, and eventually it was easier to just edit the template (or the one in the final .jar-file). it seems to be disabled at the moment... - is this correct?

...and speaking of the properties: what's the `fake_dep` annotator?

**Comment by jplu** [comment]
Works perfectly for the usage I'm doing of it :)

**Comment by ziorufus** [comment]
@iiegn You can use the `-c` parameter to use your own properties file. The properties in the file are added to the defaults, overwriting the existing ones (but leaving the other ones included in the default file and not specified in the custom one).

The `fake_dep` annotator fills the `CoNLLDepTypeAnnotation` and `CoNLLDepParentIndexAnnotation` slots with the Stanford parser annotation. It is not mandatory, of course.

**Comment by aleSuglia** [comment]
Any update about this issue? When will the Stanford latest version be supported by Tint?

Thank you for your great work guys!

Alessandro

**Comment by ziorufus** [comment]
The `develop` branch already works, you need to compile it using Maven.

**Comment by aleSuglia** [comment]
Ok fine. Thank you for your prompt answer!

**Comment by jplu** [comment]
An idea when it will be released? The corenlp370 branch works fine for me :)

**Comment by ziorufus** [comment]
Tint v0.2 is fully compatible with the new version(s) of CoreNLP.
